// <auto-generated />
namespace InfnetTecCsharpCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pedido_CamposObrigatorios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pedido_CamposObrigatorios));
        
        string IMigrationMetadata.Id
        {
            get { return "201904122235132_Pedido_CamposObrigatorios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
